endoscopy/urls.py
from django.contrib import admin
from django.urls import path, include
from endostemplates.views import home_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view, name='homepage'),
    path('templates/', include('endostemplates.urls')),
    path('registration/', include('endosreg.urls')),
]

endosreg/urls.py
from django.urls import path
from . import views

app_name = 'endosreg'

urlpatterns = [
    path('patient', views.PatientList.as_view(), name='patient_page'),
    path('patient/new', views.PatientCreate.as_view(), name='patient_new'),
    path('patient/view/<int:pk>', views.PatientView.as_view(), name='patient_view'),
    path('patient/update/<int:pk>', views.PatientUpdate.as_view(), name='patient_update'),
    path('patient/delete/<int:pk>', views.PatientDelete.as_view(), name='patient_delete'),

    path('patient/media', views.MediaList.as_view(), name='media_page'),

    path('patient/image/<int:pk>', views.ImageList.as_view(), name='image_page'),
    path('patient/image/new', views.ImageCreate.as_view(), name='image_new'),
    path('patient/image/update/<int:pk>', views.ImageUpdate.as_view(), name='image_update'),
    path('patient/image/delete/<int:pk>', views.ImageDelete.as_view(), name='image_delete'),
]

endosreg/models.py
from django.db import models
from django.utils.timezone import now
from endostemplates.models import Anesthesia

# Create your models here.
class EndosPatient(models.Model):
    name        = models.CharField(max_length=150, blank=False)
    date_birth  = models.DateField(default='1990-12-20')
    id_number   = models.CharField(max_length=9, blank=True)
    #anesthesia  = models.CharField(max_length=250)
    anesthesia  = models.ForeignKey(Anesthesia, on_delete=models.PROTECT)
    diagnosis   = models.TextField(blank=False, null=True)
    diagnosis_date = models.DateTimeField(default=now, editable=False)
    def __str__(self):
        return self.name

class EndosImage(models.Model):
    patient = models.ForeignKey(EndosPatient, on_delete=models.CASCADE)
    description = models.TextField(blank=True, null=True)
    url = models.ImageField(upload_to='static/patients')

endosreg/forms.py
from django import forms
from .models import EndosPatient, EndosImage

class PatientRegForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(PatientRegForm, self).__init__(*args, **kwargs)
        self.fields['name'].widget.attrs = {
            'class': 'form-control',
        }

        self.fields['date_birth'].widget.attrs = {
            'class': 'form-control',
        }

        self.fields['id_number'].widget.attrs = {
            'class': 'form-control',
        }

        self.fields['anesthesia'].widget.attrs = {
            'class': 'form-control',
        }

        self.fields['diagnosis'].widget.attrs = {
            'class': 'form-control',
            'rows': 8
        }

    class Meta:
        model = EndosPatient
        fields = [
            'name',
            'date_birth',
            'id_number',
            'anesthesia',
            'diagnosis'
        ]

class PatientImageForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(PatientImageForm, self).__init__(*args, **kwargs)
        self.fields['patient'].widget.attrs = {
            'class': 'form-control',
        }

        self.fields['description'].widget.attrs = {
            'class': 'form-control',
            'rows': 5
        }

        self.fields['url'].widget.attrs = {
            'class': 'form-control',
        }

    class Meta:
        model = EndosImage
        fields = [
            'patient',
            'description',
            'url',
        ]

endosreg/views.py
#from django.shortcuts import render
from django.views import generic
from .models import EndosPatient, EndosImage
from django.urls import reverse_lazy, reverse
from endosreg.forms import PatientRegForm, PatientImageForm
# Create your views here.

class PatientList(generic.ListView):
    template_name = 'patient_list.html'
    model = EndosPatient
    paginate_by = 10
    def get_queryset(self):
        return EndosPatient.objects.all().order_by("-pk")

class PatientView(generic.DetailView):
    template_name = 'patient_detail.html'
    model = EndosPatient

    def get_context_data(self, **kwargs):
        context = super(PatientView, self).get_context_data(**kwargs)
        context['patient'] = EndosPatient.objects.all()
        context['images'] = EndosImage.objects.filter(patient=self.kwargs.get('pk'))
        return context

class PatientCreate(generic.CreateView):
    template_name = 'patient_form.html'
    model = EndosPatient
    form_class = PatientRegForm
    success_url = reverse_lazy('endosreg:patient_page')

class PatientUpdate(generic.UpdateView):
    template_name = 'patient_form.html'
    model = EndosPatient
    form_class = PatientRegForm
    success_url = reverse_lazy('endosreg:patient_page')

class PatientDelete(generic.DeleteView):
    template_name = 'patient_delete.html'
    model = EndosPatient
    success_url = reverse_lazy('endosreg:patient_page')


class ImageList(generic.ListView):
    template_name = 'image_list.html'
    model = EndosImage
    def get_queryset(self):
        return EndosImage.objects.filter(patient=self.kwargs.get('pk'))

class ImageCreate(generic.CreateView):
    template_name = 'image_form.html'
    model = EndosImage
    form_class = PatientImageForm
    success_url = reverse_lazy('endosreg:media_page')

class ImageUpdate(generic.UpdateView):
    template_name = 'image_form.html'
    model = EndosImage
    form_class = PatientImageForm
    success_url = reverse_lazy('endosreg:patient_page')

class ImageDelete(generic.DeleteView):
    template_name = 'image_delete.html'
    model = EndosImage
    success_url = reverse_lazy('endosreg:patient_page')


class MediaList(generic.ListView):
    template_name = 'image_list.html'
    model = EndosImage
    def get_queryset(self):
        return EndosImage.objects.all()

endosreg/templates/image_delete.html
{% extends 'base.html' %}
{% block content_list %}

<h1 class="my-4">Delete -
        <small> Image </small>
    </h1>
    <div class="row">
        <div class="col-12">
            <form method="post">
                {% csrf_token %}
                <div class="alert alert-info" role="alert">
                    Are you sure to delete image ?
                    <p> <img style="height: 200px" src="{% url 'homepage' %}{{ object.url }}"> </p>
                </div>
                <input type="submit" class="btn btn-outline-danger" value="Yes, delete it" />
                <a class="btn btn-outline-info" href="{% url 'endosreg:patient_page' %}">Cancel</a>
            </form>
        </div>
    </div>

{% endblock %}

endosreg/templates/image_form.html
{% extends 'base.html' %}
{% block content_list %}

    <div class="d-flex">

<div class="col-6">
    <p class="h3">
        {% if request.path == '/registration/patient/image/new' %} Add Image {% else %} Edit Image {% endif %}
        {% if request.path != '/registration/patient/image/update' %}<small>{{ object.name }}</small>{% endif %}
    </p>
    <br>
    <form method="post" enctype="multipart/form-data"> {% csrf_token %}

        <div class="form-group">

            {{ form.as_p }}

        </div>

        <input type="submit" class="btn btn-outline-primary" {% if request.path == '/registration/patient/image/new' %} value="Add new" {% else %} value="Update" {% endif %}>
    </form>

</div>

    {% if request.path == '/registration/patient/image/new' %}

    {% else %}
    <div class="col-6">
        <p class="h4"> Current image </p>
        <img width="300px" src="{% url 'homepage' %}{{ object.url }}">
    </div>
    {% endif %}

</div>

{% endblock %}

endosreg/templates/image_list.html
{% extends 'base.html' %}
{% block content_list %}

<div class="col-12">
<div style="display: flex; justify-content: space-between; margin-top: 10px;">
    <p class="h3">Images list</p>
    <div>
        <a href="{% url 'endosreg:image_new' %}" class="btn btn-outline-primary"> Add Image </a>
    </div>
</div>
    <hr>

<div class="d-flex flex-row flex-wrap justify-content-around">
{% for instance in object_list %}
        <div class="card mr-4 mb-4 imagehover" style="width: 260px;">
            <a href="{% url 'homepage' %}{{ instance.url }}" target="_blank">
                <img src="{% url 'homepage' %}{{ instance.url }}" class="card-img-top">
            </a>
          <div class="card-body">
{#            <h5 class="card-title">Description</h5>#}
            <p class="card-text"> {{ instance.description }} </p>
          </div>
        <div class="d-flex justify-content-around align-text-bottom">
            <td> <a href="{% url 'endosreg:image_update' instance.id %}"><i class="material-icons">&#xE254;</i></a> </td>
            <td> <a href="{% url 'endosreg:image_delete' instance.id %}" ><i class="material-icons">&#xE872;</i></a> </td>
        </div>
        </div>
{% endfor %}
</div>


</div>

{% endblock %}

endosreg/templates/patient_delete.html
{% extends 'base.html' %}
{% block content_list %}

<h1 class="my-4">Delete -
        <small>{{ object.name }}</small>
    </h1>
    <div class="row">
        <div class="col-12">
            <form method="post">
                {% csrf_token %}
                <div class="alert alert-info" role="alert">
                    Are you sure to delete <strong> {{ object.name }} </strong> ?
                </div>
                <input type="submit" class="btn btn-outline-danger" value="Yes, delete it" />
                <a class="btn btn-outline-info" href="{% url 'endosreg:patient_page' %}">Cancel</a>
            </form>
        </div>
    </div>


{% endblock %}

endosreg/templates/patient_detail.html
{% extends 'without_menu.html' %}
{% block content_list %}

    <style>
        td {
            border: 1px solid gray !important;
            font-size: 20px;
            line-height: 26px;
        }
    </style>

    <div class="container-fluid">

        <div class="col-12 m-4">
            <p class="h4 text-center"> ЎЗБЕКИСТОН РЕСПУБЛИКАСИ ССВ НАВОИЙ ВИЛОЯТИ ССБ </p>
            <p class="h5 text-center">Навоий вилояти кўп тармоқли тиббиёт маркази маслахат поликлиникаси эндоскопия хонаси </p>
        </div>

        <table class="table table-bordered col-12">
            <tbody>
                <tr>
                    <td> <strong> ФИШ: </strong> {{ object.name }}, {{ object.date_birth }} </td>
                    <td> <strong> Анестезия: </strong> {{ object.anesthesia }} </td>
                </tr>
                <tr>
                    <td> <strong> Аппарат: </strong> Видеопроцессор «PENTAX» (Япония), Р-0,8 см. </td>
                    <td> <strong> Кўрик вақти: </strong> {% load tz %} {% timezone 'Asia/Tashkent' %} {{ object.diagnosis_date }} {% endtimezone %} </td>
                </tr>
                <tr>
                    <td colspan="2"> <strong> Ташхис: </strong> {{ object.diagnosis }} </td>
                </tr>
            </tbody>
        </table>

        <div class="d-flex flex-row flex-wrap">
            {% for image in images %}
                <table class="table-sm table-bordered col-6">
                    <tr>
                       <td class="text-center"> <img width="380px" height="380px" src="{% url 'homepage' %}{{ image.url }}" alt=""> </td>
                    </tr>
                    <tr>
                        <td class="text-center"> {{ image.description }} </td>
                    </tr>
                </table>
            {% endfor %}
        </div>
        <div class="container"> <p class="h5 text-center mt-3"> Врач-эндоскопист: О.У.Равшанов. </p> </div>
    </div>

{% endblock %}

endosreg/templates/patient_form.html
{% extends 'base.html' %}
{% block content_list %}

<div class="col-12">

<div style="display: flex; flex-direction: column; margin: 20px;" class="col-12">
    <p class="h3">
        {% if request.path == '/registration/patient/new' %} Add Patient {% else %} Edit - {% endif %}
        {% if request.path != '/registration/patient/update' %}<small>{{ object.name }}</small>{% endif %}
    </p>
    <br>
    <form method="post"> {% csrf_token %}

        <div class="form-group">

            <div class="row">
                <div class="col-6">
                    <label for="">{{ form.name.label }}</label>
                    {{ form.name }}
                </div>
                <div class="col-6">
                    <label for="">{{ form.date_birth.label }} </label>
                    {{ form.date_birth }}
                </div>
            </div>

            <div class="row mt-4">
                <div class="col-6">
                    <label for="">{{ form.id_number.label }}</label>
                    {{ form.id_number }}
                </div>
                <div class="col-6">
                    <label for="">{{ form.anesthesia.label }} </label>
                    {{ form.anesthesia }}
                </div>
            </div>

            <div class="row mt-4">
                <div class="col-12">
                    <label for=""> {{ form.diagnosis.label }} </label>
                    {{ form.diagnosis }}
                </div>
            </div>

        </div>

        <input type="submit" class="btn btn-outline-primary" {% if request.path == '/registration/patient/new' %} value="Add new" {% else %} value="Update" {% endif %}>
    </form>

</div>

</div>


{% endblock %}

endosreg/templates/patient_list.html
{% extends 'base.html' %}
{% block content_list %}

<div class="col-12">
<div style="display: flex; justify-content: space-between; margin-top: 10px;">
    <p class="h3">Patients list</p>
    <div>
        <a href="{% url 'endosreg:patient_new' %}" class="btn btn-outline-primary"> Add patient </a>
    </div>
</div>

<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center pagination">
        <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1"><small>On page <strong>{{ page_obj.number }}</strong>. Showing <strong>{{ page_obj.object_list.count }}</strong> of total <strong>{{ page_obj.paginator.count }}</strong> items.</small></a>
        </li>
    </ul>
</nav>

    <table class="table table-bordered table-sm">
      <thead class="thead-light">
        <tr>
          <th scope="col" class="text-center">№</th>
          <th scope="col">Patient</th>
          <th scope="col">Date Birth</th>
          <th scope="col">ID num</th>
          <th scope="col">Diagnosis Date</th>

          <th></th>
          <th></th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
    {% for instance in object_list %}
        <tr>
             <td class="text-center" style="width: 5%;">{{ forloop.counter0|add:page_obj.start_index }}</td>

             <td> {{ instance.name }}</td>
             <td> {{ instance.date_birth }}</td>
             <td> {{ instance.id_number }}</td>
            {% load tz %}
            {% timezone 'Asia/Tashkent' %}
             <td> {{ instance.diagnosis_date|date:'M. j, y, G:i' }}</td>
            {% endtimezone %}

             <td style="text-align: center; width: 5%;"> <a href="{% url 'endosreg:patient_view' instance.id %}" target="_blank"><i class="material-icons">search</i></a> </td>
             <td style="text-align: center; width: 5%;"> <a href="{% url 'endosreg:image_page' instance.id %}"><i class="material-icons">add_a_photo</i></a> </td>
             <td style="text-align: center; width: 5%;"> <a href="{% url 'endosreg:patient_update' instance.id %}"><i class="material-icons">&#xE254;</i></a> </td>
             <td style="text-align: center; width: 5%;"> <a href="{% url 'endosreg:patient_delete' instance.id %}" style="color: darkred"><i class="material-icons">&#xE872;</i></a> </td>
        </tr>
    {% endfor %}
      </tbody>
    </table>


{% if is_paginated %}
<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center pagination">
        {% if page_obj.has_previous %}
          <!-- If it ain't a search result display, don't append the search query
               to the URL. -->
          {% if not search %}
          <li class="page-item">
              <a class="page-link" href="{% url 'endosreg:patient_page' %}?page={{ page_obj.previous_page_number }}" tabindex="-1">Previous</a>
          </li>
          {% else %}
          <!-- Append the searched query to the URL, so that on a search results page,
               the pagination don't revert to listing all the listview items. -->
            <li class="page-item">
              <a class="page-link" href="{% url 'endosreg:patient_page' %}?{{search}}&page={{ page_obj.previous_page_number }}" tabindex="-1">Previous</a>
          </li>
          {% endif %}
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1">Previous</a>
        </li>
        {% endif %}
        {% for object in page_obj.paginator.page_range %}
            <li class="page-item"><a class="page-link" href="{% url 'endosreg:patient_page' %}?page={{ forloop.counter }}">{{ forloop.counter }}</a></li>
        {% endfor %}
        {% if page_obj.has_next %}
          {% if not search %}
          <li class="page-item">
              <a class="page-link" href="{% url 'endosreg:patient_page' %}?page={{ page_obj.next_page_number }}">Next</a>
          </li>
          {% else %}
            <li class="page-item">
              <a class="page-link" href="{% url 'endosreg:patient_page' %}?{{search}}&page={{ page_obj.next_page_number }}">Next</a>
          </li>
          {% endif %}
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" href="#">Next</a>
        </li>
        {% endif %}
    </ul>
</nav>
{% endif %}

</div>


{% endblock %}