endoscopy/urls.py
from django.contrib import admin
from django.urls import path, include
from endostemplates.views import home_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view, name='homepage'),
    path('templates/', include('endostemplates.urls')),
    path('registration/', include('endosreg.urls')),
]

endosreg/urls.py
from django.urls import path
from . import views

app_name = 'endosreg'

urlpatterns = [
    path('patient', views.PatientList.as_view(), name='patient_page'),
    path('patient/new', views.PatientCreate.as_view(), name='patient_new'),
    path('patient/view/<int:pk>', views.PatientView.as_view(), name='patient_view'),
    path('patient/update/<int:pk>', views.PatientUpdate.as_view(), name='patient_update'),
    path('patient/delete/<int:pk>', views.PatientDelete.as_view(), name='patient_delete'),

    path('patient/media', views.MediaList.as_view(), name='media_page'),

    path('patient/image/<int:pk>', views.ImageList.as_view(), name='image_page'),
    path('patient/image/new', views.ImageCreate.as_view(), name='image_new'),
    path('patient/image/update/<int:pk>', views.ImageUpdate.as_view(), name='image_update'),
    path('patient/image/delete/<int:pk>', views.ImageDelete.as_view(), name='image_delete'),
]

endostemplates/urls.py
from django.urls import path
from . import views

app_name = 'endostemplates'
urlpatterns = [
    path('device', views.DeviceView.as_view(), name='device_page'),
    path('device/new', views.DeviceCreate.as_view(), name='device_new'),
    path('device/update/<int:pk>', views.DeviceUpdate.as_view(), name='device_update'),
    path('device/delete/<int:pk>', views.DeviceDelete.as_view(), name='device_delete'),

    path('anesthesia', views.AnesthesiaView.as_view(), name='anesthesia_page'),
    path('anesthesia/new', views.AnesthesiaCreate.as_view(), name='anesthesia_new'),
    path('anesthesia/update/<int:pk>', views.AnesthesiaUpdate.as_view(), name='anesthesia_update'),
    path('anesthesia/delete/<int:pk>', views.AnesthesiaDelete.as_view(), name='anesthesia_delete'),

    path('diagnosistemplate', views.TemplateDiagnosisView.as_view(), name='diagnosistemplate_page'),
    path('diagnosistemplate/new', views.TemplateDiagnosisCreate.as_view(), name='diagnosistemplate_new'),
    path('diagnosistemplate/update/<int:pk>', views.TemplateDiagnosisUpdate.as_view(), name='diagnosistemplate_update'),
    path('diagnosistemplate/delete/<int:pk>', views.TemplateDiagnosisDelete.as_view(), name='diagnosistemplate_delete'),
]

endostemplates/models.py
from django.db import models

# Create your models here.
class Device(models.Model):
    name = models.CharField(max_length=255)
    def __str__(self):
        return self.name

class Anesthesia(models.Model):
    name = models.CharField(max_length=255)
    def __str__(self):
        return self.name

class TemplateDiagnosis(models.Model):
    title       = models.CharField(max_length=255, blank=False)
    diagnosis   = models.TextField(blank=False)
    def __str__(self):
        return self.title

endostemplates/forms.py
# Import forms
from django import forms

from .models import Device, Anesthesia, TemplateDiagnosis

class DeviceForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(DeviceForm, self).__init__(*args, **kwargs)
        self.fields['name'].widget.attrs = {
            'class': 'form-control'
        }

    class Meta:
        model = Device
        fields = ['name']

class AnesthesiaForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(AnesthesiaForm, self).__init__(*args, **kwargs)
        self.fields['name'].widget.attrs = {
            'class': 'form-control'
        }

    class Meta:
        model = Anesthesia
        fields = ['name']

class TemplateDiagnosisForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(TemplateDiagnosisForm, self).__init__(*args, **kwargs)
        self.fields['title'].widget.attrs = {
            'class': 'form-control'
        }
        self.fields['diagnosis'].widget.attrs = {
            'class': 'form-control',
            'rows': '12'
        }

    class Meta:
        model = TemplateDiagnosis
        fields = ['title', 'diagnosis']

endostemplates/views.py
from django.shortcuts import render
from django.views import generic
from .models import Device, Anesthesia, TemplateDiagnosis
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from endostemplates.forms import DeviceForm, AnesthesiaForm, TemplateDiagnosisForm
from django.urls import reverse_lazy
# Create your views here.

def home_view(request, *args, **kwargs):
    return render(request, 'templates/base.html', {})


class DeviceView(generic.ListView):
    template_name = 'device_list.html'
    model = Device
    paginate_by = 10
    def get_queryset(self):
        return Device.objects.all().order_by("-pk")

class DeviceCreate(CreateView):
    template_name = 'endostemplates/templates/device_form.html'
    model = Device
    form_class = DeviceForm
    success_url = reverse_lazy('endostemplates:device_page')
    # success_url = '../device'

class DeviceUpdate(UpdateView):
    template_name = 'endostemplates/templates/device_form.html'
    model = Device
    form_class = DeviceForm
    success_url = reverse_lazy('endostemplates:device_page')

class DeviceDelete(DeleteView):
    template_name = 'device_delete.html'
    model = Device
    success_url = reverse_lazy('endostemplates:device_page')


class AnesthesiaView(generic.ListView):
    template_name = 'anesthesia_list.html'
    paginate_by = 10
    def get_queryset(self):
        return Anesthesia.objects.all().order_by("-pk")

class AnesthesiaCreate(CreateView):
    template_name = 'endostemplates/templates/anesthesia_form.html'
    model = Anesthesia
    form_class = AnesthesiaForm
    success_url = reverse_lazy('endostemplates:anesthesia_page')

class AnesthesiaUpdate(UpdateView):
    template_name = 'endostemplates/templates/anesthesia_form.html'
    model = Anesthesia
    form_class = AnesthesiaForm
    success_url = reverse_lazy('endostemplates:anesthesia_page')

class AnesthesiaDelete(DeleteView):
    template_name = 'anesthesia_delete.html'
    model = Anesthesia
    success_url = reverse_lazy('endostemplates:anesthesia_page')


class TemplateDiagnosisView(generic.ListView):
    template_name = 'diagnosis_list.html'
    paginate_by = 5
    def get_queryset(self):
        return TemplateDiagnosis.objects.all().order_by("-pk")

class TemplateDiagnosisCreate(CreateView):
    template_name = 'endostemplates/templates/diagnosis_form.html'
    model = TemplateDiagnosis
    form_class = TemplateDiagnosisForm
    success_url = reverse_lazy('endostemplates:diagnosistemplate_page')

class TemplateDiagnosisUpdate(UpdateView):
    template_name = 'endostemplates/templates/diagnosis_form.html'
    model = TemplateDiagnosis
    form_class = TemplateDiagnosisForm
    success_url = reverse_lazy('endostemplates:diagnosistemplate_page')

class TemplateDiagnosisDelete(DeleteView):
    template_name = 'diagnosis_delete.html'
    model = TemplateDiagnosis
    success_url = reverse_lazy('endostemplates:diagnosistemplate_page')

endostemplates/templates/anesthesia_delete.html
{% extends 'base.html' %}
{% block content_list %}

<h1 class="my-4">Delete -
        <small>{{ object.name }}</small>
    </h1>
    <div class="row">
        <div class="col-12">
            <form method="post">
                {% csrf_token %}
                <div class="alert alert-info" role="alert">
                    Are you sure to delete <strong> {{ object.name }} </strong> ?
                </div>
                <input type="submit" class="btn btn-outline-danger" value="Yes, delete it" />
                <a class="btn btn-outline-info" href="{% url 'endostemplates:anesthesia_page' %}">Cancel</a>
            </form>
        </div>
    </div>


{% endblock %}

endostemplates/templates/anesthesia_form.html
{% extends 'base.html' %}
{% block content_list %}

<div class="col-12">

<div style="display: flex; flex-direction: column; margin: 20px;" class="col-6">
    <p class="h3">
        {% if request.path == '/templates/anesthesia/new' %} Add New Anesthesia Method {% else %} Edit - {% endif %}
        {% if request.path != '/templates/anesthesia/edit' %}<small>{{ anesthesia.name }}</small>{% endif %}
    </p>
    <br>
    <form method="post"> {% csrf_token %}

                    <div class="form-group">
                        {{ form.as_p }}
                    </div>
        <input type="submit" class="btn btn-outline-primary" {% if request.path == '/templates/anesthesia/new' %} value="Add new" {% else %} value="Update" {% endif %}>
    </form>
</div>

</div>


{% endblock %}

endostemplates/templates/anesthesia_list.html
{% extends 'base.html' %}
{% block content_list %}

<div class="col-12">

<div style="display: flex; justify-content: space-between; margin-top: 10px;">
    <p class="h3">Anesthesia list</p>
    <a href="{% url 'endostemplates:anesthesia_new' %}" class="btn btn-outline-primary"> Add new </a>
</div>

<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center pagination">
        <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1"><small>On page <strong>{{ page_obj.number }}</strong>. Showing <strong>{{ page_obj.object_list.count }}</strong> of total <strong>{{ page_obj.paginator.count }}</strong> items.</small></a>
        </li>
    </ul>
</nav>

    <table class="table table-bordered table-sm">
      <thead class="thead-light">
        <tr>
          <th scope="col" class="text-center">№</th>
          <th scope="col">Title</th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
    {% for instance in object_list %}
        <tr>
             <td class="text-center" style="width: 12%;">{{ forloop.counter0|add:page_obj.start_index }}</td>
             <td> <a href='{% url 'endostemplates:anesthesia_update' instance.id %}'>{{ instance.name }}</a> </td>
             <td style="text-align: center; width: 10%;"> <a href="{% url 'endostemplates:anesthesia_update' instance.id %}"><i class="material-icons">&#xE254;</i></a> </td>
             <td style="text-align: center; width: 10%;"> <a href="{% url 'endostemplates:anesthesia_delete' instance.id %}" style="color: darkred"><i class="material-icons">&#xE872;</i></a> </td>
        </tr>
    {% endfor %}
      </tbody>
    </table>

{% if is_paginated %}
<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center pagination">
        {% if page_obj.has_previous %}
          <!-- If it ain't a search result display, don't append the search query
               to the URL. -->
          {% if not search %}
          <li class="page-item">
              <a class="page-link" href="{% url 'endostemplates:anesthesia_page' %}?page={{ page_obj.previous_page_number }}" tabindex="-1">Previous</a>
          </li>
          {% else %}
          <!-- Append the searched query to the URL, so that on a search results page,
               the pagination don't revert to listing all the listview items. -->
            <li class="page-item">
              <a class="page-link" href="{% url 'endostemplates:anesthesia_page' %}?{{search}}&page={{ page_obj.previous_page_number }}" tabindex="-1">Previous</a>
          </li>
          {% endif %}
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1">Previous</a>
        </li>
        {% endif %}
        {% for object in page_obj.paginator.page_range %}
            <li class="page-item"><a class="page-link" href="{% url 'endostemplates:anesthesia_page' %}?page={{ forloop.counter }}">{{ forloop.counter }}</a></li>
        {% endfor %}
        {% if page_obj.has_next %}
          {% if not search %}
          <li class="page-item">
              <a class="page-link" href="{% url 'endostemplates:anesthesia_page' %}?page={{ page_obj.next_page_number }}">Next</a>
          </li>
          {% else %}
            <li class="page-item">
              <a class="page-link" href="{% url 'endostemplates:anesthesia_page' %}?{{search}}&page={{ page_obj.next_page_number }}">Next</a>
          </li>
          {% endif %}
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" href="#">Next</a>
        </li>
        {% endif %}
    </ul>
</nav>
{% endif %}

</div>


{% endblock %}

endostemplates/templates/delete_confirm.html
{% extends 'base.html' %}
{% block content_list %}

<h1 class="my-4">Delete -
        <small>{{ object.name }}</small>
    </h1>
    <div class="row">
        <div class="col-12">
            <form method="post">
                {% csrf_token %}
                <div class="alert alert-info" role="alert">
                    Are you sure to delete <strong> {{ object.name }} </strong> ?
                </div>
                <input type="submit" class="btn btn-outline-danger" value="Yes, delete it" />
                <a class="btn btn-outline-info" href="../../device">Cancel</a>
            </form>
        </div>
    </div>


{% endblock %}

endostemplates/templates/device_delete.html
{% extends 'base.html' %}
{% block content_list %}

<h1 class="my-4">Delete -
        <small>{{ object.name }}</small>
    </h1>
    <div class="row">
        <div class="col-12">
            <form method="post">
                {% csrf_token %}
                <div class="alert alert-info" role="alert">
                    Are you sure to delete <strong> {{ object.name }} </strong> ?
                </div>
                <input type="submit" class="btn btn-outline-danger" value="Yes, delete it" />
                <a class="btn btn-outline-info" href="{% url 'endostemplates:device_page' %}">Cancel</a>
            </form>
        </div>
    </div>


{% endblock %}

endostemplates/templates/device_form.html
{% extends 'base.html' %}
{% block content_list %}

<div class="col-12">

<div style="display: flex; flex-direction: column; margin: 20px;" class="col-6">
    <p class="h3">
        {% if request.path == '/templates/device/new' %} Add New Device {% else %} Edit - {% endif %}
        {% if request.path != '/templates/device/edit' %}<small>{{ device.name }}</small>{% endif %}
    </p>
    <br>
    <form method="post"> {% csrf_token %}

                    <div class="form-group">
                        {{ form.as_p }}
                    </div>
        <input type="submit" class="btn btn-outline-primary" {% if request.path == '/templates/device/new' %} value="Add new" {% else %} value="Update" {% endif %}>
    </form>
</div>

</div>


{% endblock %}

endostemplates/templates/device_list.html
{% extends 'base.html' %}
{% block content_list %}

<div class="col-12">
<div style="display: flex; justify-content: space-between; margin-top: 10px;">
    <p class="h3">

    {% if request.path == '/templates/device' %}  Device list
    {% elif request.path == '/templates/anesthesia' %} Anesthesia list
    {% endif %}

    </p>
    <a href="{% url 'endostemplates:device_new' %}" class="btn btn-outline-primary"> Add new </a>
</div>

<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center pagination">
        <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1"><small>On page <strong>{{ page_obj.number }}</strong>. Showing <strong>{{ page_obj.object_list.count }}</strong> of total <strong>{{ page_obj.paginator.count }}</strong> items.</small></a>
        </li>
    </ul>
</nav>

    <table class="table table-bordered table-sm">
      <thead class="thead-light">
        <tr>
          <th scope="col" class="text-center">№</th>
          <th scope="col">Title</th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
    {% for instance in object_list %}
        <tr>
             <td class="text-center" style="width: 12%;">{{ forloop.counter0|add:page_obj.start_index }}</td>
             <td> <a href='{% url 'endostemplates:device_update' instance.id %}'>{{ instance.name }}</a> </td>
             <td style="text-align: center; width: 10%;"> <a href="{% url 'endostemplates:device_update' instance.id %}"><i class="material-icons">&#xE254;</i></a> </td>
             <td style="text-align: center; width: 10%;"> <a href="{% url 'endostemplates:device_delete' instance.id %}" style="color: darkred"><i class="material-icons">&#xE872;</i></a> </td>
        </tr>
    {% endfor %}
      </tbody>
    </table>


{% if is_paginated %}
<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center pagination">
        {% if page_obj.has_previous %}
          <!-- If it ain't a search result display, don't append the search query
               to the URL. -->
          {% if not search %}
          <li class="page-item">
              <a class="page-link" href="{% url 'endostemplates:device_page' %}?page={{ page_obj.previous_page_number }}" tabindex="-1">Previous</a>
          </li>
          {% else %}
          <!-- Append the searched query to the URL, so that on a search results page,
               the pagination don't revert to listing all the listview items. -->
            <li class="page-item">
              <a class="page-link" href="{% url 'endostemplates:device_page' %}?{{search}}&page={{ page_obj.previous_page_number }}" tabindex="-1">Previous</a>
          </li>
          {% endif %}
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1">Previous</a>
        </li>
        {% endif %}
        {% for object in page_obj.paginator.page_range %}
            <li class="page-item"><a class="page-link" href="{% url 'endostemplates:device_page' %}?page={{ forloop.counter }}">{{ forloop.counter }}</a></li>
        {% endfor %}
        {% if page_obj.has_next %}
          {% if not search %}
          <li class="page-item">
              <a class="page-link" href="{% url 'endostemplates:device_page' %}?page={{ page_obj.next_page_number }}">Next</a>
          </li>
          {% else %}
            <li class="page-item">
              <a class="page-link" href="{% url 'endostemplates:device_page' %}?{{search}}&page={{ page_obj.next_page_number }}">Next</a>
          </li>
          {% endif %}
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" href="#">Next</a>
        </li>
        {% endif %}
    </ul>
</nav>
{% endif %}

</div>


{% endblock %}

endostemplates/templates/diagnosis_delete.html
{% extends 'base.html' %}
{% block content_list %}

<h1 class="my-4">Delete -
        <small>{{ object.title }}</small>
    </h1>
    <div class="row">
        <div class="col-12">
            <form method="post">
                {% csrf_token %}
                <div class="alert alert-info" role="alert">
                    Are you sure to delete <strong> {{ object.title }} </strong> ?
                </div>
                <input type="submit" class="btn btn-outline-danger" value="Yes, delete it" />
                <a class="btn btn-outline-info" href="{% url 'endostemplates:diagnosistemplate_page' %}">Cancel</a>
            </form>
        </div>
    </div>


{% endblock %}

endostemplates/templates/diagnosis_form.html
{% extends 'base.html' %}
{% block content_list %}

<div class="col-12">

<div style="display: flex; flex-direction: column; margin: 20px;" class="col-12">
    <p class="h3">
        {% if request.path == '/templates/diagnosistemplate/new' %} Add New Template of Diagnosis {% else %} Edit - {% endif %}
        {% if request.path != '/templates/diagnosistemplate/edit' %}<small>{{ object.title }}</small>{% endif %}
    </p>
    <br>
    <form method="post"> {% csrf_token %}

                    <div class="form-group">
                        {{ form.as_p }}
                    </div>
        <input type="submit" class="btn btn-outline-primary" {% if request.path == '/templates/templatediagnosis/new' %} value="Add new" {% else %} value="Update" {% endif %}>
    </form>
</div>

</div>


{% endblock %}

endostemplates/templates/diagnosis_list.html
{% extends 'base.html' %}
{% block content_list %}

<div class="col-12">

<div style="display: flex; justify-content: space-between; margin-top: 10px;">
    <p class="h3"> Template of Diagnosis List </p>
    <a href="{% url 'endostemplates:diagnosistemplate_new' %}" class="btn btn-outline-primary"> Add new </a>
</div>

<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center pagination">
        <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1"><small>On page <strong>{{ page_obj.number }}</strong>. Showing <strong>{{ page_obj.object_list.count }}</strong> of total <strong>{{ page_obj.paginator.count }}</strong> items.</small></a>
        </li>
    </ul>
</nav>

    <table class="table table-bordered table-sm">
      <thead class="thead-light">
        <tr>
          <th scope="col" class="text-center">№</th>
          <th scope="col">Title</th>
          <th scope="col">Description</th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
    {% for instance in object_list %}
        <tr>
             <td class="text-center" style="width: 5%;">{{ forloop.counter0|add:page_obj.start_index }}</td>
             <td> <a href='{% url 'endostemplates:diagnosistemplate_update' instance.id %}'>{{ instance.title }}</a> </td>
             <td style="font-size: 14px;"> {{ instance.diagnosis }} </td>
             <td style="text-align: center; width: 5%;"> <a href="{% url 'endostemplates:diagnosistemplate_update' instance.id %}"><i class="material-icons">&#xE254;</i></a> </td>
             <td style="text-align: center; width: 5%;"> <a href="{% url 'endostemplates:diagnosistemplate_delete' instance.id %}" style="color: darkred"><i class="material-icons">&#xE872;</i></a> </td>
        </tr>
    {% endfor %}
      </tbody>
    </table>

{% if is_paginated %}
<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center pagination">
        {% if page_obj.has_previous %}
          <!-- If it ain't a search result display, don't append the search query
               to the URL. -->
          {% if not search %}
          <li class="page-item">
              <a class="page-link" href="{% url 'endostemplates:diagnosistemplate_page' %}?page={{ page_obj.previous_page_number }}" tabindex="-1">Previous</a>
          </li>
          {% else %}
          <!-- Append the searched query to the URL, so that on a search results page,
               the pagination don't revert to listing all the listview items. -->
            <li class="page-item">
              <a class="page-link" href="{% url 'endostemplates:diagnosistemplate_page' %}?{{search}}&page={{ page_obj.previous_page_number }}" tabindex="-1">Previous</a>
          </li>
          {% endif %}
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1">Previous</a>
        </li>
        {% endif %}
        {% for object in page_obj.paginator.page_range %}
            <li class="page-item"><a class="page-link" href="{% url 'endostemplates:diagnosistemplate_page' %}?page={{ forloop.counter }}">{{ forloop.counter }}</a></li>
        {% endfor %}
        {% if page_obj.has_next %}
          {% if not search %}
          <li class="page-item">
              <a class="page-link" href="{% url 'endostemplates:diagnosistemplate_page' %}?page={{ page_obj.next_page_number }}">Next</a>
          </li>
          {% else %}
            <li class="page-item">
              <a class="page-link" href="{% url 'endostemplates:diagnosistemplate_page' %}?{{search}}&page={{ page_obj.next_page_number }}">Next</a>
          </li>
          {% endif %}
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" href="#">Next</a>
        </li>
        {% endif %}
    </ul>
</nav>
{% endif %}


</div>


{% endblock %}

endostemplates/templates/templates_form.html
{% extends 'base.html' %}
{% block content_list %}

<div class="col-12">

<div style="display: flex; flex-direction: column; margin: 20px;" class="col-6">
    <p class="h3">
        {% if request.path == '/templates/device/new' %} Add New Device {% else %} Edit - {% endif %}
        {% if request.path != '/templates/device/edit' %}<small>{{ device.name }}</small>{% endif %}
    </p>
    <br>
    <form method="post"> {% csrf_token %}

                    <div class="form-group">
                        {{ form.as_p }}
                    </div>
        <input type="submit" class="btn btn-outline-primary" {% if request.path == '/templates/device/new' %} value="Add new" {% else %} value="Update" {% endif %}>
    </form>
</div>

</div>


{% endblock %}