endoscopy/urls.py
from django.contrib import admin
from django.urls import path, include
from endostemplates.views import home_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view, name='homepage'),
    path('templates/', include('endostemplates.urls')),
    path('registration/', include('endosreg.urls')),
]

endosreg/urls.py
from django.urls import path
from . import views

app_name = 'endosreg'

urlpatterns = [
    path('patient', views.PatientList.as_view(), name='patient_page'),
    path('patient/new', views.PatientCreate.as_view(), name='patient_new'),
    path('patient/view/<int:pk>', views.PatientView.as_view(), name='patient_view'),
    path('patient/update/<int:pk>', views.PatientUpdate.as_view(), name='patient_update'),
    path('patient/delete/<int:pk>', views.PatientDelete.as_view(), name='patient_delete'),

    path('patient/media', views.MediaList.as_view(), name='media_page'),

    path('patient/image/<int:pk>', views.ImageList.as_view(), name='image_page'),
    path('patient/image/new', views.ImageCreate.as_view(), name='image_new'),
    path('patient/image/update/<int:pk>', views.ImageUpdate.as_view(), name='image_update'),
    path('patient/image/delete/<int:pk>', views.ImageDelete.as_view(), name='image_delete'),
]

endostemplates/urls.py
from django.urls import path
from . import views

app_name = 'endostemplates'
urlpatterns = [
    path('device', views.DeviceView.as_view(), name='device_page'),
    path('device/new', views.DeviceCreate.as_view(), name='device_new'),
    path('device/update/<int:pk>', views.DeviceUpdate.as_view(), name='device_update'),
    path('device/delete/<int:pk>', views.DeviceDelete.as_view(), name='device_delete'),

    path('anesthesia', views.AnesthesiaView.as_view(), name='anesthesia_page'),
    path('anesthesia/new', views.AnesthesiaCreate.as_view(), name='anesthesia_new'),
    path('anesthesia/update/<int:pk>', views.AnesthesiaUpdate.as_view(), name='anesthesia_update'),
    path('anesthesia/delete/<int:pk>', views.AnesthesiaDelete.as_view(), name='anesthesia_delete'),

    path('diagnosistemplate', views.TemplateDiagnosisView.as_view(), name='diagnosistemplate_page'),
    path('diagnosistemplate/new', views.TemplateDiagnosisCreate.as_view(), name='diagnosistemplate_new'),
    path('diagnosistemplate/update/<int:pk>', views.TemplateDiagnosisUpdate.as_view(), name='diagnosistemplate_update'),
    path('diagnosistemplate/delete/<int:pk>', views.TemplateDiagnosisDelete.as_view(), name='diagnosistemplate_delete'),
]

templates/base.html
{% load static %}
<!Doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/icon.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Django app</title>
  </head>
  <body>

        <div class="wrapper">
        <!-- Sidebar  -->
        <nav id="sidebar">
            <div class="sidebar-header">
                <h4><a href="{% url 'homepage' %}">Endoscopy registration</a></h4>
            </div>

            <ul class="list-unstyled components">
                <p>Menu</p>
                <li>
                    <a href="{% url 'endosreg:patient_page' %}">Patients</a>
                </li>
                <li>
                    <a href="{% url 'endosreg:media_page' %}">Media (endoscopy images)</a>
                </li>
                <li>
                    <a href="{% url 'endostemplates:device_page' %}">Device</a>
                </li>
                <li>
                    <a href="{% url 'endostemplates:anesthesia_page' %}">Anesthesia</a>
                </li>
                <li>
                    <a href="{% url 'endostemplates:diagnosistemplate_page' %}">Diagnosis templates</a>
                </li>
            </ul>
        </nav>

        <!-- Page Content  -->
        <div id="content" style="background: whitesmoke;">
            {% block content_list %}
                <div class="text-center">
                   <img height="550px" src="{% static 'img/intro.webp' %}" alt="">
                   <p style="font-size: 26px;"> Endoscopy Patient Registration System </p>
                </div>
            {% endblock %}
        </div>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
  </body>
</html>

templates/without_menu.html
{% load static %}
<!Doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <title>Django app</title>
  </head>
  <body>

        <!-- Page Content  -->
        <div id="content">

            {% block content_list %}
                tables
            {% endblock %}


        </div>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
  </body>
</html>